// This file is generated by kconfig_compiler_kf5 from dolphin_versioncontrolsettings.kcfg.
// All changes you do to this file will be lost.
#ifndef VERSIONCONTROLSETTINGS_H
#define VERSIONCONTROLSETTINGS_H

#include <kconfigskeleton.h>
#include <QCoreApplication>
#include <QDebug>

class VersionControlSettings : public KConfigSkeleton
{
  public:

    static VersionControlSettings *self();
    ~VersionControlSettings();

    /**
      Set Enabled plugins
    */
    static
    void setEnabledPlugins( const QStringList & v )
    {
      if (!self()->isImmutable( QStringLiteral( "enabledPlugins" ) ))
        self()->mEnabledPlugins = v;
    }

    /**
      Get Enabled plugins
    */
    static
    QStringList enabledPlugins()
    {
      return self()->mEnabledPlugins;
    }

  protected:
    VersionControlSettings();
    friend class VersionControlSettingsHelper;


    // VersionControl
    QStringList mEnabledPlugins;

  private:
};

#endif

