// This file is generated by kconfig_compiler_kf5 from dolphin_iconsmodesettings.kcfg.
// All changes you do to this file will be lost.

#include "dolphin_iconsmodesettings.h"

IconsModeSettings::IconsModeSettings(  )
  : KConfigSkeleton( QStringLiteral( "dolphinrc" ) )
{
  setCurrentGroup( QStringLiteral( "IconsMode" ) );

  KConfigSkeleton::ItemInt  *itemArrangement;
  itemArrangement = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "Arrangement" ), mArrangement, QListView::TopToBottom );
  addItem( itemArrangement, QStringLiteral( "Arrangement" ) );
  KConfigSkeleton::ItemBool  *itemUseSystemFont;
  itemUseSystemFont = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "UseSystemFont" ), mUseSystemFont, true );
  addItem( itemUseSystemFont, QStringLiteral( "UseSystemFont" ) );
  KConfigSkeleton::ItemString  *itemFontFamily;
  itemFontFamily = new KConfigSkeleton::ItemString( currentGroup(), QStringLiteral( "FontFamily" ), mFontFamily, KGlobalSettings::generalFont().family() );
  addItem( itemFontFamily, QStringLiteral( "FontFamily" ) );
  KConfigSkeleton::ItemDouble  *itemFontSize;
  itemFontSize = new KConfigSkeleton::ItemDouble( currentGroup(), QStringLiteral( "FontSize" ), mFontSize, KGlobalSettings::generalFont().pointSizeF() );
  addItem( itemFontSize, QStringLiteral( "FontSize" ) );
  KConfigSkeleton::ItemBool  *itemItalicFont;
  itemItalicFont = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ItalicFont" ), mItalicFont, false );
  addItem( itemItalicFont, QStringLiteral( "ItalicFont" ) );
  KConfigSkeleton::ItemInt  *itemFontWeight;
  itemFontWeight = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "FontWeight" ), mFontWeight, 0 );
  addItem( itemFontWeight, QStringLiteral( "FontWeight" ) );
  KConfigSkeleton::ItemInt  *itemItemHeight;
  itemItemHeight = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "ItemHeight" ), mItemHeight, KIconLoader::SizeMedium + QFontMetrics(KGlobalSettings::generalFont()).height() * 2 + 10 );
  addItem( itemItemHeight, QStringLiteral( "ItemHeight" ) );
  KConfigSkeleton::ItemInt  *itemItemWidth;
  itemItemWidth = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "ItemWidth" ), mItemWidth, 96 );
  addItem( itemItemWidth, QStringLiteral( "ItemWidth" ) );
  KConfigSkeleton::ItemInt  *itemGridSpacing;
  itemGridSpacing = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "GridSpacing" ), mGridSpacing, 8 );
  addItem( itemGridSpacing, QStringLiteral( "GridSpacing" ) );
  KConfigSkeleton::ItemInt  *itemIconSize;
  itemIconSize = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "IconSize" ), mIconSize, KIconLoader::SizeMedium );
  addItem( itemIconSize, QStringLiteral( "IconSize" ) );
  KConfigSkeleton::ItemInt  *itemNumberOfTextlines;
  itemNumberOfTextlines = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "NumberOfTextlines" ), mNumberOfTextlines, 2 );
  addItem( itemNumberOfTextlines, QStringLiteral( "NumberOfTextlines" ) );
  KConfigSkeleton::ItemInt  *itemPreviewSize;
  itemPreviewSize = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "PreviewSize" ), mPreviewSize, KIconLoader::SizeHuge );
  addItem( itemPreviewSize, QStringLiteral( "PreviewSize" ) );
}

IconsModeSettings::~IconsModeSettings()
{
}

