// This file is generated by kconfig_compiler_kf5 from dolphin_searchsettings.kcfg.
// All changes you do to this file will be lost.

#include "dolphin_searchsettings.h"

#include <qglobal.h>
#include <QtCore/QFile>

class SearchSettingsHelper
{
  public:
    SearchSettingsHelper() : q(nullptr) {}
    ~SearchSettingsHelper() { delete q; }
    SearchSettings *q;
};
Q_GLOBAL_STATIC(SearchSettingsHelper, s_globalSearchSettings)
SearchSettings *SearchSettings::self()
{
  if (!s_globalSearchSettings()->q) {
    new SearchSettings;
    s_globalSearchSettings()->q->read();
  }

  return s_globalSearchSettings()->q;
}

SearchSettings::SearchSettings(  )
  : KConfigSkeleton( QStringLiteral( "dolphinrc" ) )
{
  Q_ASSERT(!s_globalSearchSettings()->q);
  s_globalSearchSettings()->q = this;
  setCurrentGroup( QStringLiteral( "Search" ) );

  KConfigSkeleton::ItemString  *itemLocation;
  itemLocation = new KConfigSkeleton::ItemString( currentGroup(), QStringLiteral( "Location" ), mLocation, QStringLiteral( "FromHere" ) );
  addItem( itemLocation, QStringLiteral( "Location" ) );
  KConfigSkeleton::ItemString  *itemWhat;
  itemWhat = new KConfigSkeleton::ItemString( currentGroup(), QStringLiteral( "What" ), mWhat, QStringLiteral( "FileName" ) );
  addItem( itemWhat, QStringLiteral( "What" ) );
  KConfigSkeleton::ItemBool  *itemShowFacetsWidget;
  itemShowFacetsWidget = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowFacetsWidget" ), mShowFacetsWidget, false );
  addItem( itemShowFacetsWidget, QStringLiteral( "ShowFacetsWidget" ) );
}

SearchSettings::~SearchSettings()
{
  s_globalSearchSettings()->q = nullptr;
}

