// This file is generated by kconfig_compiler_kf5 from dolphin_iconsmodesettings.kcfg.
// All changes you do to this file will be lost.
#ifndef ICONSMODESETTINGS_H
#define ICONSMODESETTINGS_H

#include <qglobal.h>
#include <kconfigskeleton.h>
#include <QCoreApplication>
#include <QDebug>

#include <kglobalsettings.h>
#include <kiconloader.h>
#include <QListView>
class IconsModeSettings : public KConfigSkeleton
{
  public:

    IconsModeSettings( );
    ~IconsModeSettings();

    /**
      Set Arrangement
    */
    void setArrangement( int v )
    {
      if (!isImmutable( QStringLiteral( "Arrangement" ) ))
        mArrangement = v;
    }

    /**
      Get Arrangement
    */
    int arrangement() const
    {
      return mArrangement;
    }

    /**
      Set Use system font
    */
    void setUseSystemFont( bool v )
    {
      if (!isImmutable( QStringLiteral( "UseSystemFont" ) ))
        mUseSystemFont = v;
    }

    /**
      Get Use system font
    */
    bool useSystemFont() const
    {
      return mUseSystemFont;
    }

    /**
      Set Font family
    */
    void setFontFamily( const QString & v )
    {
      if (!isImmutable( QStringLiteral( "FontFamily" ) ))
        mFontFamily = v;
    }

    /**
      Get Font family
    */
    QString fontFamily() const
    {
      return mFontFamily;
    }

    /**
      Set Font size
    */
    void setFontSize( double v )
    {
      if (!isImmutable( QStringLiteral( "FontSize" ) ))
        mFontSize = v;
    }

    /**
      Get Font size
    */
    double fontSize() const
    {
      return mFontSize;
    }

    /**
      Set Italic
    */
    void setItalicFont( bool v )
    {
      if (!isImmutable( QStringLiteral( "ItalicFont" ) ))
        mItalicFont = v;
    }

    /**
      Get Italic
    */
    bool italicFont() const
    {
      return mItalicFont;
    }

    /**
      Set Font weight
    */
    void setFontWeight( int v )
    {
      if (!isImmutable( QStringLiteral( "FontWeight" ) ))
        mFontWeight = v;
    }

    /**
      Get Font weight
    */
    int fontWeight() const
    {
      return mFontWeight;
    }

    /**
      Set Item height
    */
    void setItemHeight( int v )
    {
      if (!isImmutable( QStringLiteral( "ItemHeight" ) ))
        mItemHeight = v;
    }

    /**
      Get Item height
    */
    int itemHeight() const
    {
      return mItemHeight;
    }

    /**
      Set Item width
    */
    void setItemWidth( int v )
    {
      if (!isImmutable( QStringLiteral( "ItemWidth" ) ))
        mItemWidth = v;
    }

    /**
      Get Item width
    */
    int itemWidth() const
    {
      return mItemWidth;
    }

    /**
      Set Grid spacing
    */
    void setGridSpacing( int v )
    {
      if (!isImmutable( QStringLiteral( "GridSpacing" ) ))
        mGridSpacing = v;
    }

    /**
      Get Grid spacing
    */
    int gridSpacing() const
    {
      return mGridSpacing;
    }

    /**
      Set Icon size
    */
    void setIconSize( int v )
    {
      if (!isImmutable( QStringLiteral( "IconSize" ) ))
        mIconSize = v;
    }

    /**
      Get Icon size
    */
    int iconSize() const
    {
      return mIconSize;
    }

    /**
      Set Number of textlines
    */
    void setNumberOfTextlines( int v )
    {
      if (!isImmutable( QStringLiteral( "NumberOfTextlines" ) ))
        mNumberOfTextlines = v;
    }

    /**
      Get Number of textlines
    */
    int numberOfTextlines() const
    {
      return mNumberOfTextlines;
    }

    /**
      Set Preview size
    */
    void setPreviewSize( int v )
    {
      if (!isImmutable( QStringLiteral( "PreviewSize" ) ))
        mPreviewSize = v;
    }

    /**
      Get Preview size
    */
    int previewSize() const
    {
      return mPreviewSize;
    }

  protected:

    // IconsMode
    int mArrangement;
    bool mUseSystemFont;
    QString mFontFamily;
    double mFontSize;
    bool mItalicFont;
    int mFontWeight;
    int mItemHeight;
    int mItemWidth;
    int mGridSpacing;
    int mIconSize;
    int mNumberOfTextlines;
    int mPreviewSize;

  private:
};

#endif

