// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef DOLPHIN_VERSION_H
#define DOLPHIN_VERSION_H

#define DOLPHIN_VERSION_STRING "18.03.70"
#define DOLPHIN_VERSION_MAJOR 18
#define DOLPHIN_VERSION_MINOR 03
#define DOLPHIN_VERSION_PATCH 70
#define DOLPHIN_VERSION ((18<<16)|(03<<8)|(70))

#endif
