// This file is generated by kconfig_compiler_kf5 from dolphin_searchsettings.kcfg.
// All changes you do to this file will be lost.
#ifndef SEARCHSETTINGS_H
#define SEARCHSETTINGS_H

#include <kconfigskeleton.h>
#include <QCoreApplication>
#include <QDebug>

class SearchSettings : public KConfigSkeleton
{
  public:

    static SearchSettings *self();
    ~SearchSettings();

    /**
      Set Location
    */
    static
    void setLocation( const QString & v )
    {
      if (!self()->isImmutable( QStringLiteral( "Location" ) ))
        self()->mLocation = v;
    }

    /**
      Get Location
    */
    static
    QString location()
    {
      return self()->mLocation;
    }

    /**
      Set What
    */
    static
    void setWhat( const QString & v )
    {
      if (!self()->isImmutable( QStringLiteral( "What" ) ))
        self()->mWhat = v;
    }

    /**
      Get What
    */
    static
    QString what()
    {
      return self()->mWhat;
    }

    /**
      Set Show facets widget
    */
    static
    void setShowFacetsWidget( bool v )
    {
      if (!self()->isImmutable( QStringLiteral( "ShowFacetsWidget" ) ))
        self()->mShowFacetsWidget = v;
    }

    /**
      Get Show facets widget
    */
    static
    bool showFacetsWidget()
    {
      return self()->mShowFacetsWidget;
    }

  protected:
    SearchSettings();
    friend class SearchSettingsHelper;


    // Search
    QString mLocation;
    QString mWhat;
    bool mShowFacetsWidget;

  private:
};

#endif

