// This file is generated by kconfig_compiler_kf5 from dolphin_placespanelsettings.kcfg.
// All changes you do to this file will be lost.
#ifndef PLACESPANELSETTINGS_H
#define PLACESPANELSETTINGS_H

#include <kconfigskeleton.h>
#include <QCoreApplication>
#include <QDebug>

class PlacesPanelSettings : public KConfigSkeleton
{
  public:

    static PlacesPanelSettings *self();
    ~PlacesPanelSettings();

    /**
      Set Size of icons in the Places Panel (-1 means "use the style's small size")
    */
    static
    void setIconSize( int v )
    {
      if (!self()->isImmutable( QStringLiteral( "IconSize" ) ))
        self()->mIconSize = v;
    }

    /**
      Get Size of icons in the Places Panel (-1 means "use the style's small size")
    */
    static
    int iconSize()
    {
      return self()->mIconSize;
    }

  protected:
    PlacesPanelSettings();
    friend class PlacesPanelSettingsHelper;


    // PlacesPanel
    int mIconSize;

  private:
};

#endif

