// This file is generated by kconfig_compiler_kf5 from dolphin_generalsettings.kcfg.
// All changes you do to this file will be lost.

#include "dolphin_generalsettings.h"

GeneralSettings::GeneralSettings(  )
  : KConfigSkeleton( QStringLiteral( "dolphinrc" ) )
{
  setCurrentGroup( QStringLiteral( "General" ) );

  KConfigSkeleton::ItemBool  *itemEditableUrl;
  itemEditableUrl = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "EditableUrl" ), mEditableUrl, false );
  addItem( itemEditableUrl, QStringLiteral( "EditableUrl" ) );
  QList<KConfigSkeleton::ItemEnum::Choice> valuesUrlCompletionMode;
  KConfigSkeleton::ItemEnum  *itemUrlCompletionMode;
  itemUrlCompletionMode = new KConfigSkeleton::ItemEnum( currentGroup(), QStringLiteral( "UrlCompletionMode" ), mUrlCompletionMode, valuesUrlCompletionMode, KGlobalSettings::completionMode() );
  addItem( itemUrlCompletionMode, QStringLiteral( "UrlCompletionMode" ) );
  KConfigSkeleton::ItemBool  *itemShowFullPath;
  itemShowFullPath = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowFullPath" ), mShowFullPath, false );
  addItem( itemShowFullPath, QStringLiteral( "ShowFullPath" ) );
  KConfigSkeleton::ItemBool  *itemFirstRun;
  itemFirstRun = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "FirstRun" ), mFirstRun, true );
  addItem( itemFirstRun, QStringLiteral( "FirstRun" ) );
  KConfigSkeleton::ItemInt  *itemVersion;
  itemVersion = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "Version" ), mVersion, 0 );
  addItem( itemVersion, QStringLiteral( "Version" ) );
  KConfigSkeleton::ItemBool  *itemModifiedStartupSettings;
  itemModifiedStartupSettings = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ModifiedStartupSettings" ), mModifiedStartupSettings, false );
  addItem( itemModifiedStartupSettings, QStringLiteral( "ModifiedStartupSettings" ) );
  KConfigSkeleton::ItemString  *itemHomeUrl;
  itemHomeUrl = new KConfigSkeleton::ItemString( currentGroup(), QStringLiteral( "HomeUrl" ), mHomeUrl, QDir::homePath() );
  addItem( itemHomeUrl, QStringLiteral( "HomeUrl" ) );
  KConfigSkeleton::ItemBool  *itemSplitView;
  itemSplitView = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "SplitView" ), mSplitView, false );
  addItem( itemSplitView, QStringLiteral( "SplitView" ) );
  KConfigSkeleton::ItemBool  *itemFilterBar;
  itemFilterBar = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "FilterBar" ), mFilterBar, true );
  addItem( itemFilterBar, QStringLiteral( "FilterBar" ) );
  KConfigSkeleton::ItemBool  *itemGlobalViewProps;
  itemGlobalViewProps = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "GlobalViewProps" ), mGlobalViewProps, true );
  addItem( itemGlobalViewProps, QStringLiteral( "GlobalViewProps" ) );
  KConfigSkeleton::ItemBool  *itemBrowseThroughArchives;
  itemBrowseThroughArchives = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "BrowseThroughArchives" ), mBrowseThroughArchives, false );
  addItem( itemBrowseThroughArchives, QStringLiteral( "BrowseThroughArchives" ) );
  KConfigSkeleton::ItemBool  *itemConfirmClosingMultipleTabs;
  itemConfirmClosingMultipleTabs = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ConfirmClosingMultipleTabs" ), mConfirmClosingMultipleTabs, true );
  addItem( itemConfirmClosingMultipleTabs, QStringLiteral( "ConfirmClosingMultipleTabs" ) );
  KConfigSkeleton::ItemBool  *itemRenameInline;
  itemRenameInline = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "RenameInline" ), mRenameInline, false );
  addItem( itemRenameInline, QStringLiteral( "RenameInline" ) );
  KConfigSkeleton::ItemBool  *itemShowSelectionToggle;
  itemShowSelectionToggle = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowSelectionToggle" ), mShowSelectionToggle, true );
  addItem( itemShowSelectionToggle, QStringLiteral( "ShowSelectionToggle" ) );
  KConfigSkeleton::ItemBool  *itemShowToolTips;
  itemShowToolTips = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowToolTips" ), mShowToolTips, false );
  addItem( itemShowToolTips, QStringLiteral( "ShowToolTips" ) );
  KConfigSkeleton::ItemBool  *itemShowCopyMoveMenu;
  itemShowCopyMoveMenu = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowCopyMoveMenu" ), mShowCopyMoveMenu, false );
  addItem( itemShowCopyMoveMenu, QStringLiteral( "ShowCopyMoveMenu" ) );
  KConfigSkeleton::ItemDateTime  *itemViewPropsTimestamp;
  itemViewPropsTimestamp = new KConfigSkeleton::ItemDateTime( currentGroup(), QStringLiteral( "ViewPropsTimestamp" ), mViewPropsTimestamp );
  addItem( itemViewPropsTimestamp, QStringLiteral( "ViewPropsTimestamp" ) );
  KConfigSkeleton::ItemBool  *itemAutoExpandFolders;
  itemAutoExpandFolders = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "AutoExpandFolders" ), mAutoExpandFolders, true );
  addItem( itemAutoExpandFolders, QStringLiteral( "AutoExpandFolders" ) );
  KConfigSkeleton::ItemBool  *itemShowZoomSlider;
  itemShowZoomSlider = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowZoomSlider" ), mShowZoomSlider, true );
  addItem( itemShowZoomSlider, QStringLiteral( "ShowZoomSlider" ) );
  KConfigSkeleton::ItemBool  *itemShowSpaceInfo;
  itemShowSpaceInfo = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowSpaceInfo" ), mShowSpaceInfo, true );
  addItem( itemShowSpaceInfo, QStringLiteral( "ShowSpaceInfo" ) );
  KConfigSkeleton::ItemBool  *itemLockPanels;
  itemLockPanels = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "LockPanels" ), mLockPanels, true );
  addItem( itemLockPanels, QStringLiteral( "LockPanels" ) );
}

GeneralSettings::~GeneralSettings()
{
}

