// This file is generated by kconfig_compiler_kf5 from dolphin_informationpanelsettings.kcfg.
// All changes you do to this file will be lost.
#ifndef INFORMATIONPANELSETTINGS_H
#define INFORMATIONPANELSETTINGS_H

#include <kconfigskeleton.h>
#include <QCoreApplication>
#include <QDebug>

class InformationPanelSettings : public KConfigSkeleton
{
  public:

    static InformationPanelSettings *self();
    ~InformationPanelSettings();

    /**
      Set Previews shown
    */
    static
    void setPreviewsShown( bool v )
    {
      if (!self()->isImmutable( QStringLiteral( "previewsShown" ) ))
        self()->mPreviewsShown = v;
    }

    /**
      Get Previews shown
    */
    static
    bool previewsShown()
    {
      return self()->mPreviewsShown;
    }

  protected:
    InformationPanelSettings();
    friend class InformationPanelSettingsHelper;


    // InformationPanel
    bool mPreviewsShown;

  private:
};

#endif

