// This file is generated by kconfig_compiler_kf5 from dolphin_directoryviewpropertysettings.kcfg.
// All changes you do to this file will be lost.

#include "dolphin_directoryviewpropertysettings.h"

ViewPropertySettings::ViewPropertySettings(  KSharedConfig::Ptr config  )
  : KConfigSkeleton( config )
{
  setCurrentGroup( QStringLiteral( "Settings" ) );

  KConfigSkeleton::ItemBool  *itemShowHiddenFiles;
  itemShowHiddenFiles = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowDotFiles" ), mShowHiddenFiles, false );
  addItem( itemShowHiddenFiles, QStringLiteral( "ShowHiddenFiles" ) );
  KConfigSkeleton::ItemStringList  *itemHideSpecificFiles;
  itemHideSpecificFiles = new KConfigSkeleton::ItemStringList( currentGroup(), QStringLiteral( "HideSpecificFiles" ), mHideSpecificFiles );
  addItem( itemHideSpecificFiles, QStringLiteral( "HideSpecificFiles" ) );

  setCurrentGroup( QStringLiteral( "Dolphin" ) );

  KConfigSkeleton::ItemInt  *itemVersion;
  itemVersion = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "Version" ), mVersion, 1 );
  itemVersion->setMinValue(1);
  addItem( itemVersion, QStringLiteral( "Version" ) );
  KConfigSkeleton::ItemInt  *itemViewMode;
  itemViewMode = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "ViewMode" ), mViewMode, DolphinView::ColumnView );
  itemViewMode->setMinValue(2);
  itemViewMode->setMaxValue(DolphinView::MaxModeEnum);
  addItem( itemViewMode, QStringLiteral( "ViewMode" ) );
  KConfigSkeleton::ItemBool  *itemShowPreview;
  itemShowPreview = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "ShowPreview" ), mShowPreview, false );
  addItem( itemShowPreview, QStringLiteral( "ShowPreview" ) );
  KConfigSkeleton::ItemBool  *itemCategorizedSorting;
  itemCategorizedSorting = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "CategorizedSorting" ), mCategorizedSorting, false );
  addItem( itemCategorizedSorting, QStringLiteral( "CategorizedSorting" ) );
  KConfigSkeleton::ItemInt  *itemSorting;
  itemSorting = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "Sorting" ), mSorting, DolphinView::SortByName );
  itemSorting->setMinValue(0);
  itemSorting->setMaxValue(DolphinView::MaxSortingEnum);
  addItem( itemSorting, QStringLiteral( "Sorting" ) );
  KConfigSkeleton::ItemInt  *itemSortOrder;
  itemSortOrder = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "SortOrder" ), mSortOrder, Qt::AscendingOrder );
  itemSortOrder->setMinValue(Qt::AscendingOrder);
  itemSortOrder->setMaxValue(Qt::DescendingOrder);
  addItem( itemSortOrder, QStringLiteral( "SortOrder" ) );
  KConfigSkeleton::ItemBool  *itemSortFoldersFirst;
  itemSortFoldersFirst = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "SortFoldersFirst" ), mSortFoldersFirst, true );
  addItem( itemSortFoldersFirst, QStringLiteral( "SortFoldersFirst" ) );
  KConfigSkeleton::ItemInt  *itemAdditionalInfo;
  itemAdditionalInfo = new KConfigSkeleton::ItemInt( currentGroup(), QStringLiteral( "AdditionalInfo" ), mAdditionalInfo, 0 );
  addItem( itemAdditionalInfo, QStringLiteral( "AdditionalInfo" ) );
  KConfigSkeleton::ItemStringList  *itemAdditionalInfoV2;
  itemAdditionalInfoV2 = new KConfigSkeleton::ItemStringList( currentGroup(), QStringLiteral( "AdditionalInfoV2" ), mAdditionalInfoV2 );
  addItem( itemAdditionalInfoV2, QStringLiteral( "AdditionalInfoV2" ) );
  KConfigSkeleton::ItemDateTime  *itemTimestamp;
  itemTimestamp = new KConfigSkeleton::ItemDateTime( currentGroup(), QStringLiteral( "Timestamp" ), mTimestamp );
  addItem( itemTimestamp, QStringLiteral( "Timestamp" ) );
}

ViewPropertySettings::~ViewPropertySettings()
{
}

